name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    strategy:
      matrix:
        flake: [polars-dev, turmoil]
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
        with:
          determinate: true
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "LucioFranco/${{ matrix.flake }}"
          rolling: true
          visibility: "unlisted"
          directory: ${{ matrix.flake }}
